### PR TITLE
Stylus windows

### PR DESCRIPTION
**Pull request by qdlmcfresh**

### CODE REVIEW

**Comment by AzzieDev** [comment]
Hey @qdlmcfresh would you be able to share a link to the built Windows binaries for the latest state of Weylus with the Windows API stuff you added? I'd love to test it out

**Comment by qdlmcfresh** [comment]
@AzzieDev 
[weylus.zip](https://github.com/qdlmcfresh/Weylus/files/9595270/weylus.zip)

**Comment by AzzieDev** [comment]
Thank you so much!

I'm testing this and everything seems to just work flawlessly (other than the QR code but that's nothing to do with your pull request)

**Comment by AzzieDev** [comment]
Upon further testing, the "erase" button on my stylus doesn't seem to function, it toggles-on the Settings sidebar some of the time.  Regardless, this is amazing.

Edit: Also, the more complex touch gestures seem very iffy or do not work entirely. I managed to accidentally trigger the switch-apps gesture. https://support.microsoft.com/en-us/windows/touch-gestures-for-windows-a9d28305-4818-a5df-4e2b-e5590f850741 

I'm still loving every bit of this, and might analyze the log and code a bit.

**Comment by qdlmcfresh** [comment]
@AzzieDev Just had some time to look at the erase button. At least with my surface pen i cant get any browser( well i tried chrome and firefox) to spit out a pointerevent with the correct button code.
```
altKey: false
bubbles: true
button: -1
buttons: 1
cancelBubble: false
cancelable: true
clientX: 237
clientY: 242
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
explicitOriginalTarget: Restricted {  }
height: 1
isPrimary: true
isTrusted: true
layerX: 136
layerY: 242
metaKey: false
movementX: 0
movementY: 0
mozInputSource: 1
mozPressure: 0.6193293929100037
offsetX: 0
offsetY: 0
originalTarget: Restricted {  }
pageX: 237
pageY: 242
pointerId: 0
pointerType: "mouse"
pressure: 0.6193293929100037
rangeOffset: 0
rangeParent: null
relatedTarget: null
returnValue: true
screenX: 243
screenY: 382
shiftKey: false
```
is what im getting when using my eraser, which is pretty much the same as when using the front tip.
As you can read [here](https://w3c.github.io/pointerevents/#the-button-property) the button/buttons propertie should indicate stuff like that but it seems like this isnt implemented 

Also there is an [issue](https://github.com/H-M-H/Weylus/issues/104) in the original weylus repo stating the same so i dont think i can do something about that, sorry

**Pull request merged**
